# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def app_and_tests_common_pods()
  pod 'AzureIoTUtility', '=1.5.0', :modular_headers => true
  pod 'AzureIoTuMqtt', '=1.5.0', :modular_headers => true
  pod 'AzureIoTuAmqp', '=1.5.0', :modular_headers => true
  pod 'AzureIoTHubClient', '=1.5.0', :modular_headers => true
end

target 'Wrapper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wrapper
  app_and_tests_common_pods()

  target 'WrapperTests' do
    inherit! :search_paths
    # Pods for testing
    app_and_tests_common_pods()
  end

end
